# Generated by Django 6.0.2 on 2026-02-27 16:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('room_type', models.CharField(choices=[('junior', 'Junior Suite'), ('executive', 'Executive Suite'), ('deluxe', 'Super Deluxe'), ('presidential', 'Presidential Suite'), ('family', 'Family Room')], default='junior', max_length=20)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5)),
                ('description', models.TextField()),
                ('short_description', models.CharField(help_text='Brief description for cards', max_length=200)),
                ('max_guests', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('beds', models.PositiveIntegerField(default=1, help_text='Number of beds')),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Beds')], default='queen', max_length=20)),
                ('bedrooms', models.PositiveIntegerField(default=1)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('has_wifi', models.BooleanField(default=True)),
                ('has_tv', models.BooleanField(default=True)),
                ('has_ac', models.BooleanField(default=True)),
                ('has_minibar', models.BooleanField(default=False)),
                ('has_safe', models.BooleanField(default=True)),
                ('has_balcony', models.BooleanField(default=False)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='rooms/main/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'name'],
                'indexes': [models.Index(fields=['room_type', 'is_available'], name='rooms_room_room_ty_125b19_idx'), models.Index(fields=['price_per_night'], name='rooms_room_price_p_60d0ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Font Awesome icon class (e.g., 'fa-bed')", max_length=50)),
                ('text', models.CharField(help_text="Display text (e.g., '3 Bed')", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='rooms.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/additional/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='rooms.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
