# Generated by Django 6.0.2 on 2026-02-28 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HouseRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('smoking', 'Smoking & Fire Safety'), ('property', 'Rooms & Property Care'), ('quiet', 'Peace & Quiet'), ('nature', 'Nature & Environment'), ('safety', 'Safety & Valuables'), ('conduct', 'Guest Conduct')], max_length=20)),
                ('rule', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Font Awesome icon', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LaundryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_tzs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Laundry Services',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_room_price_p_60d0ac_idx',
        ),
        migrations.AddField(
            model_name='room',
            name='has_bbq_grill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_bluetooth_speaker',
            field=models.BooleanField(default=False, help_text='Wireless speaker'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_fireplace',
            field=models.BooleanField(default=False, help_text='Fireplace for cozy evenings'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_fully_equipped_kitchen',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='has_outdoor_seating',
            field=models.BooleanField(default=True, help_text='Patio with garden views'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_private_bathroom',
            field=models.BooleanField(default=True, help_text='Private bathroom with hot shower'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_smart_tv',
            field=models.BooleanField(default=True, help_text='Smart TV with Netflix, YouTube'),
        ),
        migrations.AddField(
            model_name='room',
            name='has_umbrellas',
            field=models.BooleanField(default=False, help_text='Umbrellas for rainy days'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night_tzs',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Price in Tanzanian Shillings', max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='villa_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='has_wifi',
            field=models.BooleanField(default=True, help_text='High-Speed Internet'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('one_bedroom', 'One-Bedroom Villa'), ('two_bedroom', 'Two-Bedroom Villa'), ('family', 'Family Villa')], default='one_bedroom', max_length=20),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['price_per_night_tzs'], name='rooms_room_price_p_94cecc_idx'),
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_balcony',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_minibar',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_safe',
        ),
        migrations.RemoveField(
            model_name='room',
            name='has_tv',
        ),
        migrations.RemoveField(
            model_name='room',
            name='price_per_night',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_number',
        ),
    ]
